### ISSUE TITLE
GUI Suggestions

### ISSUE THREAD

**Issue by Jumpinqq** [ionar2/salhack#27]
Using the GUI Colors feature changes only text, but not the Icons next to each category.

1) It'd be cool if those colors could change with the text. Alternatively, you could have 2 separate color changing options rather than changing the Icons and the Text together.  

The only problem I see with this is there are slightly lighter/darker colors being used within the World, and Combat icons. If a color overlay is added that will make the color difference invisible which isn't a big issue. I don't know if this is possible but one way to fix that issue  would be to change the hue of the original image rather than doing a color overlay?

2) Another suggestion I have, within the selector category (which has a typo, "selecter")
It'd be cool if you could change the size / location of the SalHack watermark at the bottom left.

3) Also sometimes when you're hovering over a module its hard to tell if you have it enabled or not because it always becomes blue. It should stay displayed as on / off but still have the darker box when you're hovering over it.

**Comment by ionar2** [comment]
Colors not easily switchable for icons, but i did make sliders anyway, in order to fix this, these shapes would need to be directly spawned in opengl, without the png file, or change colors on the png.

I don't have more knowledge around this

Selector typo fixed.

color suggestion fixed too

PS. Keep issues in seperate threads, there are 3 issues in this one.
