### ISSUE TITLE
I would like a highway filling in feature with autobuild

### ISSUE THREAD

**Issue by Han75** [ionar2/salhack#36]
Hi! Could you add a module to autobuilder that fills the highway in with obsidian? Thanks :)

**Comment by dominikaaaa** [comment]
Use baritone or autohighwaybuilder.

**Comment by ionar2** [comment]
You can also accomplish this with flatten mode

**Comment by r-33** [comment]
> You can also accomplish this with flatten mode

you couldn't fill it in nicely due to the bedrock roof. It would just be fucky.

> Use baritone or autohighwaybuilder.

if he used baritone he would have to make four or two separate schematics for each direction. Salhack autobuiler is cool for the reason that it builds in whatever direction you're facing.

Axua made a salhack skid for mc_ren that does this "highway filling" feature so i guess its somewhat sought after. I forked the source for it it looks kinda autistic (doesn't build based on what direction you're facing) but wtvr

**Comment by dominikaaaa** [comment]
this is already finished now.
